# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taylinks
email: taylor@ponchochap.com
description: > # this means to ignore newlines until "baseurl:"
  This is Taylor Mitchell's link blog, where you can find
  excellent links.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://taylinks.com" # the base hostname & protocol for your site
twitter_username: taylorwmitchell
github_username:  taylorwmitchell
instagram_username: taylorwmitchell

# Build settings
markdown: kramdown
